@host = https://localhost
@port = 7286
@Restaurants_API_HostAddress = {{host}}:{{port}}
@token = CfDJ8Cxe0lQADtBAklYrT6JVjzXxK2BDkTq3WfDKoUYFF0DF5HYMCjKdzVO_-yylrkLJJDQ06UiVYwMtydVVds_Xly3E6Dt06zYNYReuWpAALHOWrGwJUw16ObTPuj5SQJb7_qj9l-IPQlETlZOx7ue3SgNVQ8vKETlKI3QFUbP9aOcxeyKcG9P9AlfVKkv4drWI_V7DixU1lI8dFVbnfcyS7S2YzBk9lfrs3g85PXalVsb88J0ZsYz2CARU3E7lJLcMK2famP4njVDN5UU3RrSIcHfzSwjCOcjN8tHL0Ff253TMvWYCnx01IABraZ9Gvun7rsc83hKeh9q8rDKUPv__Ggly6haGhZ7rhxvqMoWqieLBSwzfEiDrAnCzHpIV9EZmy4rJBBNlQH2rR0h76yrK-Su8tQx7PsXUqzwS1L2s-PQmh6PfdPlgrqwqubP30kIzX6tlNvcY3a93ntSKL0_Fiik82uWj3HPvp7AhVOvZxAGieVjn6jWvWOGnReTK_-lOI-70bb9DcREcj3YBB307qufOOvTbEWCWudPjuSm-LX5ZPPcmAvDhltF60gTPTbGu8L3KY5PJZFgujNgrpDQ8dyfmG_khikxHroGhr6B4u9KM0K9GM6ctPOEDSGGTHi9xNwRPcBgn9NP7DBtXjsh38POaIZ7kzQ9WSoSoHkYlwsHgap3YwTOG1fTz-vzLhvKDNA

GET {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/2
Authorization: Bearer {{token}}


###

POST {{Restaurants_API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

# {
#     "Name": "Spicy Delights",
#     "Description": "A culinary experience like no other",
#     "Category": "Fine dining",
#     "HasDelivery": true,
#     "ContactEmail": "info@gourmetdelights.com",
#     "ContactNumber": "555-123-4567",
#     "City": "Metropolis",
#     "Street": "456 Gourmet Avenue",
#     "PostalCode": "54321"
# }

{
    "PostalCode": "123"
}

###

GET {{Restaurants_API_HostAddress}}/api/restaurants/2/dishes/13
Authorization: Bearer {{token}}

###

PUT {{Restaurants_API_HostAddress}}/api/restaurants/2/dishes/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Spaghetti Bolognese",
    "Description": "Classic Italian pasta dish with rich meat sauce",
    "Price": 12.99,
    "KiloCalories": 750
}
###

POST {{Restaurants_API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants_API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}